= RelatonIso: retrieve ISO Standards for bibliographic use using the BibliographicItem model

image:https://img.shields.io/gem/v/relaton-iso.svg["Gem Version", link="https://rubygems.org/gems/relaton-iso"]
image:https://github.com/relaton/relaton-iso/workflows/macos/badge.svg["Build Status (macOS)", link="https://github.com/relaton/relaton-iso/actions?workflow=macos"]
image:https://github.com/relaton/relaton-iso/workflows/windows/badge.svg["Build Status (Windows)", link="https://github.com/relaton/relaton-iso/actions?workflow=windows"]
image:https://github.com/relaton/relaton-iso/workflows/ubuntu/badge.svg["Build Status (Ubuntu)", link="https://github.com/relaton/relaton-iso/actions?workflow=ubuntu"]
image:https://codeclimate.com/github/relaton/relaton-iso/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/metanorma/relaton-iso"]
image:https://img.shields.io/github/issues-pr-raw/relaton/relaton-iso.svg["Pull Requests", link="https://github.com/relaton/relaton-iso/pulls"]
image:https://img.shields.io/github/commits-since/relaton/relaton/latest.svg["Commits since latest",link="https://github.com/relaton/relaton/releases"]

RelatonIso is a Ruby gem that implements the https://github.com/metanorma/metanorma-model-iso#iso-bibliographic-item[IsoBibliographicItem model].

You can use it to retrieve metadata of ISO Standards from https://www.iso.org, and access such metadata through the `IsoBibliographicItem` object.

== Installation

Add this line to your application's Gemfile:

[source,ruby]
----
gem 'relaton-iso'
----

And then execute:

    $ bundle

Or install it yourself as:

    $ gem install relaton-iso

== Usage

=== Search for standards using keywords

[source,ruby]
----
require 'relaton_iso'
=> true

hit_collection = RelatonIso::IsoBibliography.search("ISO 19115")
=> <RelatonIso::HitCollection:0x007fa5bc847038 @ref=19115 @fetched=false>

hit_collection.first
=> <RelatonIso::Hit:0x007f87e71ea9f8 @text="ISO 19115" @fetched="false" @fullIdentifier="" @title="">

item = hit_collection[2].fetch
=> #<RelatonIsoBib::IsoBibliographicItem:0x007fa5dca89510
...

item.docidentifier
=> [#<RelatonIso::DocumentIdentifier:0x00007fa8b7db1f20
  @id=
   #<Pubid::Iso::Identifier:0x00007fa8b7db2a60
    @base=#<Pubid::Iso::Identifier:0x00007fa8b7db2c68 @edition="1", @number="19115"@4, @part="1", @publisher="ISO", @year=2014>,
    @number="2"@21,
    @publisher="ISO",
    @stage=#<Pubid::Iso::Stage:0x00007fa8b7db20d8 @abbr=nil, @harmonized_code=#<Pubid::Iso::HarmonizedStageCode:0x00007fa8b7db2088 @stages=["60.60"]>>,
    @typed_stage=#<Pubid::Iso::TypedStage:0x00007fa8b7db2920 @type=#<Pubid::Iso::Type:0x00007fa8b7db26c8 @type=:amd>, @typed_stage=nil>,
    @year=2020>,
  @language=nil,
  @primary=true,
  @scope=nil,
  @script=nil,
  @type="ISO">,
 #<RelatonIso::DocumentIdentifier:0x00007fa8b7db1e80
  @id=
   #<Pubid::Iso::Identifier:0x00007fa8b7db2a60
    @base=#<Pubid::Iso::Identifier:0x00007fa8b7db2c68 @edition="1", @number="19115"@4, @part="1", @publisher="ISO", @year=2014>,
    @number="2"@21,
    @publisher="ISO",
    @stage=#<Pubid::Iso::Stage:0x00007fa8b7db20d8 @abbr=nil, @harmonized_code=#<Pubid::Iso::HarmonizedStageCode:0x00007fa8b7db2088 @stages=["60.60"]>>,
    @typed_stage=#<Pubid::Iso::TypedStage:0x00007fa8b7db2920 @type=#<Pubid::Iso::Type:0x00007fa8b7db26c8 @type=:amd>, @typed_stage=nil>,
    @year=2020>,
  @language=nil,
  @primary=nil,
  @scope=nil,
  @script=nil,
  @type="URN">]

item.docidentifier.detect { |di| di.type == "URN" }.id
=> "urn:iso:std:iso:19115:-1:ed-1:amd:2020:v2"
----

=== Fetch document by reference and year

[source,ruby]
----
item = RelatonIso::IsoBibliography.get "ISO 19115:2003"
[relaton-iso] ("ISO 19115:2003") fetching from ISO...
[relaton-iso] ("ISO 19115:2003") Found exact match.
=> #<RelatonIsoBib::IsoBibliographicItem:0x00007f8c83429e30
...

item = RelatonIso::IsoBibliography.get "ISO 19115", "2003"
[relaton-iso] ("ISO 19115") fetching from ISO...
[relaton-iso] ("ISO 19115:2003") Found exact match.
=> #<RelatonIsoBib::IsoBibliographicItem:0x00007f8c828d3180
...

item.docidentifier[0].id
=> "ISO 19115:2003"
----

=== Fetch non-part document

[source,ruby]
----
item = RelatonIso::IsoBibliography.get "ISO 19115"
[relaton-iso] ("ISO 19115") fetching from ISO...
[relaton-iso] ("ISO 19115") Found ("ISO 19115:2003").
=> #<RelatonIsoBib::IsoBibliographicItem:0x00007f8c830275a8
...

item.docidentifier[0].id
=> "ISO 19115:2003"
----

=== Fetch a part document

[source,ruby]
----
item = RelatonIso::IsoBibliography.get "ISO 19115-1"
[relaton-iso] ("ISO 19115-1") fetching from ISO...
[relaton-iso] ("ISO 19115-1") Found ("ISO 19115-1:2014").
=> #<RelatonIsoBib::IsoBibliographicItem:0x00007f8c83408af0
...

item.docidentifier[0].id
=> "ISO 19115-1"
----

=== Fetch all-parts document

[source,ruby]
----
item = RelatonIso::IsoBibliography.get "ISO 19115 (all parts)"
[relaton-iso] ("ISO 19115") Fetching from ISO...
[relaton-iso] ("ISO 19115") Found exact match.
=> #<RelatonIsoBib::IsoBibliographicItem:0x00007f8ca216e118
...

item = RelatonIso::IsoBibliography.get "ISO 19115", nil, all_parts: true
[relaton-iso] ("ISO 19115") Fetching from ISO...
[relaton-iso] ("ISO 19115") Found exact match.
=> #<RelatonIsoBib::IsoBibliographicItem:0x00007f8c830f3d38
...

item.docidentifier[0].id
=> "ISO 19115 (all parts)"

item = RelatonIso::IsoBibliography.get "ISO 19115-1 (all parts)"
[relaton-iso] ("ISO 19115") Fetching from ISO...
[relaton-iso] ("ISO 19115") Found exact match.
=> #<RelatonIsoBib::IsoBibliographicItem:0x00007f8c8290e5a0

item = RelatonIso::IsoBibliography.get "ISO 19115-1", nil, all_parts: true
[relaton-iso] ("ISO 19115") Fetching from ISO...
[relaton-iso] ("ISO 19115") Found exact match.
=> #<RelatonIsoBib::IsoBibliographicItem:0x00007f8c925355b8
...

item.docidentifier[0].id
=> "ISO 19115 (all parts)"
----

=== Search for ISO/IEC Directives

The ISO/IEC Directives are stored in a static cache in a relaton gem. It needs to use the relaton gem to fetch the ISO/IEC Directives. The following references are allowed to fetch:

- ISO/IEC DIR 1 - Procedures for the technical work
- ISO/IEC DIR 1 IEC SUP - Procedures for the technical work – Procedures specific to IEC
- ISO/IEC DIR 1 ISO SUP - Consolidated ISO Supplement -- Procedures specific to ISO
- ISO/IEC DIR 2 IEC - Principles and rules for the structure and drafting of ISO and IEC documents
- ISO/IEC DIR 2 ISO - Principles and rules for the structure and drafting of ISO and IEC documents
- ISO/IEC DIR IEC SUP - Procedures specific to IEC
- ISO/IEC DIR JTC 1 SUP - Procedures specific to JTC 1

=== XML serialization

Possible options:

- *bibdata* - If true then wrapp item with _bibdata_ element and add _ext_ element.
- *note* - Array of hashes `{ text: "Note", type: "note" }`. These notes will be added to XML.

[source,ruby]
----
item.to_xml
=> "<bibitem id="ISO19115-1-2014" type="standard" schema-version="v1.2.1">
      <fetched>2022-12-04</fetched>
      <title type="title-intro" format="text/plain" language="en" script="Latn">Geographic information</title>
      <title type="title-main" format="text/plain" language="en" script="Latn">Metadata</title>
      ...
    </bibitem>"

item.to_xml bibdata: true
=> "<bibdata type="standard" schema-version="v1.2.1">
      <fetched>2022-12-04</fetched>
      <title type="title-intro" format="text/plain" language="en" script="Latn">Geographic information</title>
      ...
      <ext schema-version="v1.0.0">
        <doctype>international-standard</doctype>
        ...
      </ext>
    </bibdata>"

item.to_xml note: [{ text: "Note", type: "note" }]
=> "<bibitem id="ISO19115-1-2014" type="standard" schema-version="v1.2.1">
      ...
      <note format="text/plain" type="note">Note</note>
      ...
    </bibitem>"
----

=== Get specific language

[source,ruby]
----
item.title lang: 'en'
=> #<RelatonBib::TypedTitleStringCollection:0x00007fa8b7f47c90
 @array=
  [#<RelatonBib::TypedTitleString:0x00007fa8b7be8a40
    @title=#<RelatonBib::FormattedString:0x00007fa8b7be87c0 @content="Geographic information", @format="text/plain", @language=["en"], @script=["Latn"]>,
    @type="title-intro">,
   #<RelatonBib::TypedTitleString:0x00007fa8b7be84a0
    @title=#<RelatonBib::FormattedString:0x00007fa8b7be83d8 @content="Metadata", @format="text/plain", @language=["en"], @script=["Latn"]>,
    @type="title-main">,
   #<RelatonBib::TypedTitleString:0x00007fa8b7be8130
    @title=
     #<RelatonBib::FormattedString:0x00007fa8b7be8018
      @content="Geographic information – Metadata",
      @format="text/plain",
      @language=["en"],
      @script=["Latn"]>,
    @type="main">]>

item.title lang: 'fr'
=> #<RelatonBib::TypedTitleStringCollection:0x00007fa8b7bcb4b8
 @array=
  [#<RelatonBib::TypedTitleString:0x00007fa8b7be3ea0
    @title=#<RelatonBib::FormattedString:0x00007fa8b7be3dd8 @content="Information géographique", @format="text/plain", @language=["fr"], @script=["Latn"]>,
    @type="title-intro">,
   #<RelatonBib::TypedTitleString:0x00007fa8b7be3ba8
    @title=#<RelatonBib::FormattedString:0x00007fa8b7be3b58 @content="Métadonnées", @format="text/plain", @language=["fr"], @script=["Latn"]>,
    @type="title-main">,
   #<RelatonBib::TypedTitleString:0x00007fa8b7be38d8
    @title=
     #<RelatonBib::FormattedString:0x00007fa8b7be3860
      @content="Information géographique – Métadonnées",
      @format="text/plain",
      @language=["fr"],
      @script=["Latn"]>,
    @type="main">]>

item = RelatonIso::IsoBibliography.get "ISO 19115:2003"
[relaton-iso] ("ISO 19115:2003") Fetching from ISO...
[relaton-iso] ("ISO 19115:2003") Found exact match.
=> #<RelatonIsoBib::IsoBibliographicItem:0x00007fa8870b69e0

item.abstract lang: 'en'
item.abstract lang: 'en'
=> #<RelatonBib::FormattedString:0x00007fa8870b4f78
 @content=
  "ISO 19115:2003 defines the schema required for describing geographic information ...",
 @format="text/plain",
 @language=["en"],
 @script=["Latn"]>
----

=== Typed links

Each ISO document has `src` type link and optional `obp`, `rss`, and `pub` link types.

[source,ruby]
----
item.link
=> [#<RelatonBib::TypedUri:0x00007fa8870ac5a8
  @content=#<Addressable::URI:0xcc6514 URI:https://www.iso.org/standard/26020.html>,
  @language=nil,
  @script=nil,
  @type="src">,
 #<RelatonBib::TypedUri:0x00007fa8870a7490
  @content=#<Addressable::URI:0xcc6528 URI:https://www.iso.org/contents/data/standard/02/60/26020.detail.rss>,
  @language=nil,
  @script=nil,
  @type="rss">]
----

== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run `rake spec` to run the tests. You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and tags, and push the `.gem` file to [rubygems.org](https://rubygems.org).


== Exceptional Citations

This gem retrieves bibliographic descriptions of ISO documents by doing searches on the ISO website, http://www.iso.org, and screenscraping the document that matches the queried document identifier. The following documents are not returned as search results from the ISO website, and the gem returns manually generated references to them.

* `IEV`: used in the metanorma-iso gem to reference Electropedia entries generically. Is resolved to an "all parts" reference to IEC 60050, which in turn is resolved into the specific documents cited by their top-level clause.

== Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/metanorma/relaton-iso

== License

The gem is available as open source under the terms of the https://opensource.org/licenses/MIT[MIT license].
