# frozen_string_literal: true

# require "nokogiri"
require "net/http"
# require "logger"
require "pubid-iso"
require "relaton/index"
# require "relaton_iso_bib"
require "relaton/bib"
require_relative "iso/version"
require_relative "iso/util"
require_relative "iso/bibdata"
# require "relaton_iso/hash_converter"
# require "relaton_iso/hit"
# require "relaton_iso/iso_bibliography"
# require "relaton_iso/document_identifier"
# require "relaton_iso/index"
# require "relaton_iso/queue"
# require "relaton_iso/data_fetcher"
