# frozen_string_literal: true

require "net/http"
require "pubid/iso"
require "relaton/index"
require "isoics"
require "relaton/bib"
require "relaton/core"
require_relative "iso/version"
require_relative "iso/util"
require_relative "iso/model/item_data"
require_relative "iso/model/item"
require_relative "iso/model/relation"
require_relative "iso/model/bibitem"
require_relative "iso/model/bibdata"
require_relative "iso/hit_collection"
require_relative "iso/hit"
# require "relaton_iso/iso_bibliography"
# require "relaton_iso/document_identifier"
# require "relaton_iso/index"
# require "relaton_iso/queue"
# require "relaton_iso/data_fetcher"
